services:
  - type: web
    name: agua-rural
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: out
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
      - key: NEXT_PUBLIC_ORGANIZATION_NAME
        value: FORTE GRÃOS
      - key: NEXT_PUBLIC_FIRST_ADMIN_EMAIL
        value: jedielson.figueiredo@hotmail.com
